spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.139.137:8848
      config:
        server-addr: 47.100.139.137:8848
        namespace: gateway

    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

  application:
    name: gulimall-gateway
server:
  port: 88
